# Generated by Django 5.2.5 on 2026-02-06 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('holder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('premium_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('sum_assured', models.CharField(blank=True, max_length=50, null=True)),
                ('coverage_start_date', models.DateField(blank=True, null=True)),
                ('coverage_end_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='parser_app.insurancedocument')),
            ],
        ),
    ]
